### ISSUE TITLE
Support running existing modules without modification?

### ISSUE THREAD

**Issue by countvajhula** [benknoble/tmux-vim-demo#1]
Continuing from [Discourse](https://racket.discourse.group/t/new-interactive-tutorial-format-for-racket-libraries), can we support running existing Racket modules without needing to modify them?

> [...] at the moment, this would require users to modify an existing Racket module that they intend to run interactively (such as the Qi tutorial) by adding a header specific to tmux-vim-demo. Even using the (require tmux-vim-demo) approach with a separate runner script, they'd still need to manually enter the word racket into the Racket buffer in order to enter the Racket REPL before continuing with the rest of the module. Do you think it would be possible to support some form of "pre" step where we can run some commands before running the demo in filename (via run-demo)? I think this would make it more seamless for Vim users and could also make this package compelling to use with any existing Racket module without modification, and not only demos or tutorials.

**Comment by benknoble** [comment]
This seems entirely feasible with a syntax like

```
#:pre "commands"
```

Using something complex for `commands` would probably involve dealing with string escapes, but to use something simple like `racket` or `python3` should be easy.

**Comment by countvajhula** [comment]
🏅

**Comment by countvajhula** [comment]
I've updated the [setup instructions](https://github.com/countvajhula/qi-tutorial#vim) for Qi's tutorial to use this 👍
