### ISSUE TITLE
Avoid echoing action after sending a line to the shell

### ISSUE THREAD

**Issue by countvajhula** [benknoble/tmux-vim-demo#2]
When we hit `r` to send the current line or selection to the shell, it echoes a confirmation at the bottom of the buffer requiring the user to enter a key to dismiss it. It would be nice to be able to disable this echo since it seems unnecessary in at least some common cases and is an extra step for the user.

**Comment by benknoble** [comment]
Hm, I don't remember encountering this issue, but maybe I messed something up translating my original script into the commands. 

Can you show the result of `:map r`?

**Comment by countvajhula** [comment]
`:map r` output:

<img width="560" alt="Screen Shot 2021-12-25 at 3 41 19 PM" src="https://user-images.githubusercontent.com/401668/147395579-9baad507-e992-45f8-8336-bdec679600ec.png">

I think it happens specifically when the text is zoomed in or if the terminal window is small. E.g. if I make the window larger or zoom out via `Cmd+-` it doesn't ask for confirmation of the message even though it's still displayed. But when the window is smaller than a certain size / text zoomed in more than a certain level, it requires confirmation to dismiss it:

<img width="674" alt="Screen Shot 2021-12-25 at 3 40 02 PM" src="https://user-images.githubusercontent.com/401668/147395576-7e11e5fd-84e3-469c-b6b9-a3b4b7cac367.png">

So I guess given this, it's not essential to fix but more of an annoyance if your text happens to be zoomed in.

**Comment by countvajhula** [comment]
🎉
