### ISSUE TITLE
Support read/write mode?

### ISSUE THREAD

**Issue by countvajhula** [benknoble/tmux-vim-demo#3]
In cases arising from #1, it would be nice to be able to actually make modifications in the buffer and be able to save them -- i.e. using tmux-vim-demo as a lightweight interactive editor. The Vim buffer currently opens as Read-only, so this behavior is discouraged at the moment.

Maybe this would warrant some additional forms:

```
(run-demo ...) ; the current form, not specific to Racket (and read-only)
(run ...) ; the same as the current form but opens the module in read/write
(run-racket-demo ...) ; uses read-only
(run-racket ...) ; uses read/write
```

**Comment by benknoble** [comment]
This seems reasonable. I think my preference would be to just add another argument `#:demo?`, but I'm open to compelling justifications for an alternate approach.

From a library perspective, separate forms may make sense (as wrappers with certain arguments defaulting in a reasonable way). But I expect the main usage to be in the `#lang` form.

**Comment by countvajhula** [comment]
Adding a `#:demo?` argument works for me. The other forms e.g. `run-racket` could just be convenience forms that rewrite to `run-demo` (or whatever core form) with the appropriate values for the various arguments as you mentioned. This could make it a little more convenient to use, kind of like `tech/reference` and `tech/guide` over `tech` for Scribble - not essential, though!

**Comment by countvajhula** [comment]
🎈
